### ISSUE TITLE
assumption matrix

### ISSUE THREAD

**Issue by YarnnSom** [vanasti/KortrijkxRotterdam#29]
Bekijk slides die Tibo heeft doorgestuurd (meer op het einde, slide 22)

**Comment by vanasti** [comment]
['22-'23 UXR3 - TW2P1_ Problem space definition.pdf](https://github.com/vanasti/KortrijkxRotterdam/files/11523927/22-.23.UXR3.-.TW2P1_.Problem.space.definition.pdf)

**Comment by vanasti** [comment]
Hierboven ook de slides voor CMD-students

**Comment by vanasti** [comment]
Moet nog op de matrix geplaatst worden
